name: outbox_studio_app

description: "Outbox Media Studio Application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.0.0
  flutter_local_notifications: ^17.2.3

  # UI
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  flutter_svg: ^2.2.0
  cached_network_image: ^3.3.0
  flutter_time_picker_spinner: ^2.0.0

  # ✅ ADICIONADO - Flutter Native Splash
  flutter_native_splash: ^2.4.0

  # Backend
  supabase_flutter: ^2.5.6

  # State Management
  provider: ^6.1.2
  shared_preferences: ^2.2.2

  # Audio
  audioplayers: ^5.2.1

  # Payments - ✅ STRIPE ADICIONADO
  flutter_stripe: ^10.1.1
  http: ^1.1.0
  flutter_dotenv: ^5.1.0

  # Outras
  image_picker: ^1.1.2
  permission_handler: ^11.0.0
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ✅ CONFIGURAÇÃO DO SPLASH SCREEN
flutter_native_splash:
  color: "#0A0A0A"  # Cor de fundo escura do seu app
  image: assets/splash/logo.png  # Seu logo (crie a pasta assets/splash/)
  color_dark: "#0A0A0A"
  image_dark: assets/splash/logo.png
  android_12:
    image: assets/splash/logo.png
    icon_background_color: "#0A0A0A"
    image_dark: assets/splash/logo.png
    icon_background_color_dark: "#0A0A0A"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/splash/  # ✅ ADICIONADO
    - assets/images/
    - assets/images/icons/
    - assets/second-screen/
    - assets/fonts/
    - assets/slides-home/
    - .env # ✅ Arquivo de ambiente para Stripe keys

  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
